/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-03-02 16:32:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class AuthorMasterForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/AuthorMasterHeader.jsp", Long.valueOf(1646238582696L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Author Master Form</title>\r\n");
      out.write("</head>\r\n");
      out.write("<BODY BGCOLOR=\"pink\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<TABLE BORDER=\"1\" ALIGN=\"center\" WIDTH=\"100%\">\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD ALIGN=\"center\"><A HREF=\"javascript:alert('Goodbye');window.close();\">Logout</A></TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t\t<TR>\r\n");
      out.write("\t\t\t<TD COLSPAN=\"3\" ALIGN=\"right\">\r\n");
      out.write("\t\t\t\tDate: ");
      out.print( new java.util.Date() );
      out.write("\r\n");
      out.write("\t\t\t</TD>\r\n");
      out.write("\t\t</TR>\r\n");
      out.write("\t</TABLE>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!-- Initializing a form object, which will submit data captured on the form. --> \r\n");
      out.write("<FORM ACTION=\"AuthorMaster.jsp\" METHOD=\"post\" NAME=\"FrmAuthMast\">\r\n");
      out.write("<!-- Parent Table begins. -->\r\n");
      out.write("<TABLE ALIGN=\"center\" BGCOLOR=\"cyan\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\" NAME=\"tblOuter\" WIDTH=\"50%\">\r\n");
      out.write("<TR HEIGHT=\"300\" VALIGN=\"top\">\r\n");
      out.write("<TD ALIGN=\"center\" BORDER=\"1\" COLSPAN=\"10\"> <BR />\r\n");
      out.write("<TABLE ALIGN=\"center\" BORDER=\"1\" BORDERCOLOR=\"BLUE\" CELLPADDING=\"2\" CELLSPACING=\"0\" NAME=\"tblFirstChild\" WIDTH=\"100%\">\r\n");
      out.write("\r\n");
      out.write("<!-- Inserting table row to display the form title -->\r\n");
      out.write("<TR BGCOLOR=\"BLACK\">\r\n");
      out.write("\t<TD ALIGN=\"left\" COLSPAN=\"2\">\r\n");
      out.write("\t<!-- Formatting the font of title -->\r\n");
      out.write("\t<FONT SIZE=\"2\" COLOR=\"white\"><B>Author Master</B></FONT></TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<!--Inserting table row that holds table data label and text box of Author Name -->\r\n");
      out.write("<TR>\r\n");
      out.write("<TD ALIGN=\"right\" WIDTH=\"25%\">Author Name:</TD>\r\n");
      out.write("<TD ALIGN=\"left\"><INPUT MAXLENGTH=\"35\" NAME=\"txtAuthorName\" TYPE=\"text\" SIZE=\"25\"/></TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<!-- Inserting table row that holds table data label and text box of Degree -->\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD ALIGN=\"right\">Degree:</TD>\r\n");
      out.write("\t<TD ALIGN=\"left\">\r\n");
      out.write("\t<INPUT MAXLENGTH=\"255\" NAME=\"txtDegree\" TYPE=\"text\" SIZE=\"42\" />\r\n");
      out.write("\t</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<!-- Inserting table row that holds table data label and text box of Speciality -->\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD ALIGN=\"right\">Speciality:</TD>\r\n");
      out.write("\t<TD ALIGN=\"left\">\r\n");
      out.write("\t<INPUT MAXLENGTH=\"255\" NAME=\"txtSpeciality\" TYPE=\"text\" SIZE=\"42\" />\r\n");
      out.write("\t</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<!-- Inserting table row that holds table data lable and text box of Date of birth -->\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD ALIGN=\"right\">Date Of Birth:</TD>\r\n");
      out.write("\t<TD ALIGN=\"left\">\r\n");
      out.write("\t<INPUT MAXLENGTH=\"255\" NAME=\"txtDOB\" TYPE=\"text\" SIZE=\"\" />\r\n");
      out.write("\t</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("<!-- Inserting table row that holds inputs for Save button -->\r\n");
      out.write("<TR>\r\n");
      out.write("\t<TD COLSPAN=\"2\" ALIGN=\"RIGHT\">\r\n");
      out.write("\t<INPUT NAME=\"cmdSubmit\" TYPE=\"submit\" VALUE=\"Submit\" />\r\n");
      out.write("\t</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</TD>\r\n");
      out.write("</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</FORM>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
