/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-03-02 09:00:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    ");

   // import javax.servlet.http.HttpSession;
  //  HttpSession session = request.getSession(false); // To avoid new session creation to continue with the same session.
	
 // if((String) session.getAttribute("userName") == "Admin"){
    
    
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title> Apex International School || ADMIN</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=âbootstrap/css/bootstrap.min.cssâ rel=âstylesheetâ type=âtext/cssâ />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script type=âtext/javascriptâ src=âbootstrap/js/bootstrap.min.jsâ></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ul {\r\n");
      out.write("      list-style-type: none;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      background-color:#aebde1;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    li:last-child {\r\n");
      out.write("      border-right: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a {\r\n");
      out.write("      display: block;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 14px 16px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a:hover:not(.active) {\r\n");
      out.write("      background-color: #111;\r\n");
      out.write("    }\r\n");
      out.write("    #background{\r\n");
      out.write("        background-image: url('salambasha.png');\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-attachment: fixed;  \r\n");
      out.write("  background-size: cover;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 400px !important;\r\n");
      out.write("    \r\n");
      out.write("        margin-left: 700px;\r\n");
      out.write("    margin-top: 200px;\r\n");
      out.write("    \r\n");
      out.write("    word-break: break-word;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       <ul>\r\n");
      out.write("     \r\n");
      out.write("      <li style=\"float:right\"><a href=\"index.jsp\"><button class=\"btn btn-danger\">Logout</button></a></li>\r\n");
      out.write("      <li style=\"float:right\"><a href=\"changePassword.jsp\"><button class=\"btn btn-warning\">Change Password</button></a></li>\r\n");
      out.write("   \r\n");
      out.write("     </ul>\r\n");
      out.write("     <br><br>\r\n");
      out.write("\r\n");
      out.write("     <table class=\"table table-bordered\" style=\"width: 50%; align-items: center;\" >\r\n");
      out.write("        <thead>  Employee Management</thead>\r\n");
      out.write("        <tr style=\"align-items: center; font-weight: 800;\">\r\n");
      out.write("          <td>S.No</td>\r\n");
      out.write("          <td>Options</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>1</td>\r\n");
      out.write("          <td><div>\r\n");
      out.write("       <a href=\"addEmployee.jsp\">\r\n");
      out.write("     <button class=\"btn btn-success\"> Add Employee</button></a>\r\n");
      out.write("     </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>2</td>\r\n");
      out.write("          <td style=\"color:white;\"><div>\r\n");
      out.write("       <a href=\"employeeList.jsp\">\r\n");
      out.write("     <button class=\"btn btn-primary\"> Employee List</button></a>\r\n");
      out.write("     </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("    <!--     <tr>\r\n");
      out.write("          <td>3</td>\r\n");
      out.write("          <td><a href=\"searchEmployeeById.jsp\">Search Employee By Id</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>4</td>\r\n");
      out.write("          <td><a href=\"modEmployeeById.jsp\">Modify Employee By Id</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>5</td>\r\n");
      out.write("          <td><a href=\"delEmployeeById.jsp\">Remove By EmployeeId</a></td>\r\n");
      out.write("        </tr>        \r\n");
      out.write("        <tr> -->\r\n");
      out.write("          <td>3</td>\r\n");
      out.write("          <td><div><a href=\"listEmployeeByDept.jsp\"><button class=\"btn btn-warning\"> List By Dept</button></a></div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <!-- <tr>\r\n");
      out.write("          <td>7</td>\r\n");
      out.write("          <td><a href=\"\"></a></td>\r\n");
      out.write("        </tr> -->\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     </table>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- <h1>Assallaamu alaikkum</h1> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <table class=\"table table-bordered\">\r\n");
      out.write("      <thead class=\"thead\">\r\n");
      out.write("     <tr >\r\n");
      out.write("    \r\n");
      out.write("     <th> S.No </th>\r\n");
      out.write("     <th> Employee Id </th>\r\n");
      out.write("     <th> FirstName </th>\r\n");
      out.write("     <th> LasttName </th>\r\n");
      out.write("     <th> Address </th>\r\n");
      out.write("     <th> Department </th>\r\n");
      out.write("     <th> Basic Salary </th>\r\n");
      out.write("     <th> Gross Salary </th>\r\n");
      out.write("     <th> Actions</th>\r\n");
      out.write("     </tr>\r\n");
      out.write("   </thead>\r\n");
      out.write("   <tbody> \r\n");
      out.write("\r\n");
      out.write("     ");


     

     try {
       Class.forName("com.mysql.cj.jdbc.Driver");
       Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cyberinforminies_ems","root","basha");
       Statement st=conn.createStatement();
       
       ResultSet rs=st.executeQuery("select * from employee"); 
       int i=0;
       PrintWriter out1 = response.getWriter();
       
       while(rs.next() ){  i++; 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("           \r\n");
      out.write("             <tr>\r\n");
      out.write("             \r\n");
      out.write("       <td> ");
 out.print(i); 
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print(  rs.getInt("empId"));
      out.write("</td>\r\n");
      out.write("                   <td>");
      out.print(  rs.getString("empFName"));
      out.write("</td>\r\n");
      out.write("                   <td>");
      out.print(  rs.getString("empLastName"));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(  rs.getString("address"));
      out.write("</td>\r\n");
      out.write("                     <td>");
      out.print(  rs.getString("department"));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.print(  rs.getString("basicSalary"));
      out.write("</td>\r\n");
      out.write("                       <td>");
      out.print(  rs.getString("grossSalary"));
      out.write("</td>\r\n");
      out.write("                       <td>\r\n");
      out.write("                       <a href=\"EmployeeController?empId=");
      out.print(rs.getInt("empId"));
      out.write("\"><i class=\"bi bi-eye-fill\" style=\"padding:5px;\"></i></a>\r\n");
      out.write("                       <a href=\"EmployeeController?searchModId=");
      out.print(rs.getInt("empId"));
      out.write("\"><i class=\"bi bi-pencil-square\" style=\"padding:5px;\"></i></a>\r\n");
      out.write("                       <a href=\"EmployeeController?deleteId=");
      out.print(rs.getInt("empId"));
      out.write("\"><button onclick=\"confirm('Are you sure to delete?');\"><i class=\"bi bi-trash-fill\" style=\"padding:5px;\"></i></button></a>\r\n");
      out.write("                       \r\n");
      out.write("                       </td>\r\n");
      out.write("                   \r\n");
      out.write("              </tr>\r\n");
      out.write("             \r\n");
      out.write("         \r\n");
      out.write("       ");
 } 
       
           
         
       
   
       
       
 }catch(Exception e){
     e.printStackTrace();
    
     
 
} 
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </tbody>\r\n");
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    </body>\r\n");
      out.write("    </html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
