/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-03-02 07:37:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class employeeById_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title> Apex International School || ADMIN</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=âbootstrap/css/bootstrap.min.cssâ rel=âstylesheetâ type=âtext/cssâ />\r\n");
      out.write("<script type=âtext/javascriptâ src=âbootstrap/js/bootstrap.min.jsâ></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ul {\r\n");
      out.write("      list-style-type: none;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      background-color:#aebde1;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    li:last-child {\r\n");
      out.write("      border-right: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a {\r\n");
      out.write("      display: block;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 14px 16px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a:hover:not(.active) {\r\n");
      out.write("      background-color: #111;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  * {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text], select, textarea, input[type=email]{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  resize: vertical;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("  padding: 12px 12px 12px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit]:hover {\r\n");
      out.write("  background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-25 {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 25%;\r\n");
      out.write("  margin-top: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-75 {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 75%;\r\n");
      out.write("  margin-top: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write(".row:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: table;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .col-25, .col-75, input[type=submit] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       <ul>\r\n");
      out.write("       <li style=\"text-align:center;\"  ><h3>Apex International School</h3></li>\r\n");
      out.write("      <li style=\"float:right\"><a href=\"index.jsp\"><button class=\"btn btn-danger\">Logout</button></a></li>\r\n");
      out.write("   <!--     <li style=\"float:right\"><a href=\"changePassword.jsp\"><button class=\"btn btn-warning\">Change Password</button></a></li> -->\r\n");
      out.write("   \r\n");
      out.write("     </ul>\r\n");
      out.write("     <br><br>\r\n");



String empIds = request.getParameter("empId");
String empName = "";
ResultSet rs = null;
if(empIds!=null){
	int empId = Integer.parseInt(empIds);
	try {
    	
      Class.forName("com.mysql.cj.jdbc.Driver");
      Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cyberinforminies_ems","root","basha");
      Statement st=conn.createStatement();
      
      rs=st.executeQuery("select * from employee where empId="+empId); 
     
      rs.next();
   
        //  out.print(rs.getString("address"));
	   
    }catch(Exception e){
    	e.printStackTrace();
    }
	
   
     
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <form  method=\"post\" action = \"EmployeeController\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-25\">\r\n");
      out.write("        <label for=\"fname\">First Name</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-75\">\r\n");
      out.write("        <input type=\"text\" id=\"fname\" name=\"firstName\" value=\"");
      out.print(rs.getString("empFName") );
      out.write("\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-25\">\r\n");
      out.write("        <label for=\"lname\">Last Name</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-75\">\r\n");
      out.write("        <input type=\"text\" id=\"lname\" name=\"lastName\" value=\"");
      out.print(rs.getString("empLastName") );
      out.write("\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-25\">\r\n");
      out.write("        <label for=\"country\">Department</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-75\">\r\n");
      out.write("        <select id=\"department\" name=\"department\" value=\"");
      out.print(rs.getString("department") );
      out.write("\">\r\n");
      out.write("          <option value=\"Accounts\">Accounts</option>\r\n");
      out.write("          <option value=\"Human Resources\">Human Resources</option>\r\n");
      out.write("          <option value=\"IT\">IT</option>\r\n");
      out.write("          <option value=\"System Admin\">System Admin</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("      <div class=\"col-25\">\r\n");
      out.write("        <label for=\"salary\">Salary</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-75\">\r\n");
      out.write("        <input type=\"text\" id=\"salary\" name=\"salary\" value=\"");
      out.print(rs.getString("basicSalary") );
      out.write("\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-25\">\r\n");
      out.write("        <label for=\"address\">Address</label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-75\">\r\n");
      out.write("        <textarea id=\"address\" name=\"address\"  style=\"height:200px;word-break: break-all\">\r\n");
      out.write("        ");
      out.print(rs.getString("address") );
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        </textarea>\r\n");
      out.write("      </div>\r\n");
      out.write("      <input type=\"hidden\" name =\"updateId\"value=\"");
      out.print(empId);
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <input type=\"submit\" value=\"Submit\" style = \"text-align:center; margin-right:35vw; margin-top:20px;\"> \r\n");
      out.write("      <!-- <button type=\"submit\" class=\"btn btn-primary float-right\" style = \"text-align:center; margin-right:35vw; margin-top:20px;\">ADD</button> -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

} else{
	
	out.print("<h3> Entered id is not found </h3>");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
