/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-03-02 07:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.hibernate.internal.build.AllowSysOut;
import java.sql.*;
import java.io.*;

public final class employeeListByDept_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.internal.build.AllowSysOut");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

   // import javax.servlet.http.HttpSession;
  //  HttpSession session = request.getSession(false); // To avoid new session creation to continue with the same session.
	
 // if((String) session.getAttribute("userName") == "Admin"){
    
    
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title> Apex International School || ADMIN</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=âbootstrap/css/bootstrap.min.cssâ rel=âstylesheetâ type=âtext/cssâ />\r\n");
      out.write("<script type=âtext/javascriptâ src=âbootstrap/js/bootstrap.min.jsâ></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ul {\r\n");
      out.write("      list-style-type: none;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      background-color:#aebde1;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    li:last-child {\r\n");
      out.write("      border-right: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a {\r\n");
      out.write("      display: block;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 14px 16px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    li a:hover:not(.active) {\r\n");
      out.write("      background-color: #111;\r\n");
      out.write("    }\r\n");
      out.write("    #background{\r\n");
      out.write("        background-image: url('salambasha.png');\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-attachment: fixed;  \r\n");
      out.write("  background-size: cover;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: 400px !important;\r\n");
      out.write("    \r\n");
      out.write("        margin-left: 700px;\r\n");
      out.write("    margin-top: 200px;\r\n");
      out.write("    \r\n");
      out.write("    word-break: break-word;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       <ul>\r\n");
      out.write("     \r\n");
      out.write("      <li style=\"float:right\"><a href=\"index.jsp\"><button class=\"btn btn-danger\">Logout</button></a></li>\r\n");
      out.write("   <!--     <li style=\"float:right\"><a href=\"changePassword.jsp\"><button class=\"btn btn-warning\">Change Password</button></a></li> -->\r\n");
      out.write("   \r\n");
      out.write("     </ul>\r\n");
      out.write("     <br><br>\r\n");
      out.write("     \r\n");
      out.write("     <table class=\"table table-bordered\">\r\n");
      out.write("       <thead class=\"thead\">\r\n");
      out.write("      <tr >\r\n");
      out.write("     \r\n");
      out.write("      <th> S.No </th>\r\n");
      out.write("      <th> Employee Id </th>\r\n");
      out.write("      <th> FirstName </th>\r\n");
      out.write("      <th> LasttName </th>\r\n");
      out.write("      <th> Address </th>\r\n");
      out.write("      <th> Department </th>\r\n");
      out.write("      <th> Basic Salary </th>\r\n");
      out.write("      <th> Gross Salary </th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody> \r\n");
      out.write("\r\n");
      out.write("      ");


      
     String department = request.getParameter("department");
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/cyberinforminies_ems","root","basha");
        Statement st=conn.createStatement();
        
        ResultSet rs=st.executeQuery("select * from employee where department='"+department+"'"); 
        int i=0;
        PrintWriter out1 = response.getWriter();
        
        while(rs.next() ){  i++; 
      out.write("\r\n");
      out.write("        \t\r\n");
      out.write("        \t  \r\n");
      out.write("              <tr>\r\n");
      out.write("              \r\n");
      out.write("        <td> ");
 out.print(i); 
      out.write("</td>\r\n");
      out.write("                   <td>");
      out.print(  rs.getInt("empId"));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(  rs.getString("empFName"));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(  rs.getString("empLastName"));
      out.write("</td>\r\n");
      out.write("                     <td>");
      out.print(  rs.getString("address"));
      out.write("</td>\r\n");
      out.write("                      <td>");
      out.print(  rs.getString("department"));
      out.write("</td>\r\n");
      out.write("                       <td>");
      out.print(  rs.getString("basicSalary"));
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(  rs.getString("grossSalary"));
      out.write("</td>\r\n");
      out.write("                    \r\n");
      out.write("               </tr>\r\n");
      out.write("              \r\n");
      out.write("        \t\r\n");
      out.write("        ");
 } 
        
            if(i==0){
            	
            	out.print("<h4 style='color:red;'> Sorry No records found in this department</h4>");
            }
          
        
    
        
        
  }catch(Exception e){
      e.printStackTrace();
     
      
  
 } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("\r\n");
      out.write("     </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
